services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}  
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: nevatal_backend
    command: /app/entrypoint.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: nevatal_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: