# Generated by Django 5.2.6 on 2026-06-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chatrecord_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='api_key_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='api_key',
            field=models.TextField(default=''),
        ),
    ]
