# Generated by Django 5.2.6 on 2026-09-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatrecord_api_key_hash_alter_chatrecord_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='batch',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='tokens_in',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='tokens_out',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='method',
            field=models.CharField(choices=[('prompt', 'Prompt'), ('proofreader', 'Proofreader'), ('summarizer', 'Summarizer'), ('translator', 'Translator'), ('writer', 'Writer'), ('rewriter', 'Rewriter'), ('explainer', 'Explainer'), ('copywriting', 'Copywriting'), ('document_ai', 'Document AI'), ('email_generator', 'Email Generator'), ('rag_chat', 'RAG Chat'), ('email_generation', 'Email Generation'), ('sentiment_analysis', 'Sentiment Analysis'), ('image_generation', 'Image Generation'), ('meeting_summary', 'Meeting Summary'), ('social_media_post_generation', 'Social Media Post'), ('direct_extraction', 'Direct Extraction'), ('analyze_text', 'Analyze Text'), ('code_generation', 'Code Generation'), ('code_reviewer', 'Code Reviewer'), ('idea_generation', 'Idea Generator'), ('data_formatting', 'Data Formatter'), ('data_analysis', 'Data Analysis')], default='prompt', max_length=255),
        ),
    ]
